"use client"
import { api } from "@/services/api";
import { createContext, Dispatch, SetStateAction, useEffect, useState } from "react";
import { setCookie, } from 'nookies'
import nookies from 'nookies'
// Generated by https://quicktype.io

export interface IClientResponse {
    id: string;
    username: string;
    created_at: string;
    email: string;
    name: string;
    phone: string;
    contacts: any[];
}
export interface ITokenAccess {
    access_token: string
}

interface IAuthContext {
    profile: IClientResponse | undefined
    setProfile: Dispatch<SetStateAction<IClientResponse | undefined>>
    token: string | undefined
    setToken: Dispatch<SetStateAction<string | undefined>>,
    trigger: boolean
    setTrigger: Dispatch<SetStateAction<boolean>>
}
interface IAuthContextParams {
    children: React.ReactNode
}
export const AuthContext = createContext({} as IAuthContext)


export const AuthProvider = ({ children }: IAuthContextParams) => {
    const [profile, setProfile] = useState<IClientResponse | undefined>()
    const [token, setToken] = useState<string | undefined>()
    const [trigger, setTrigger] = useState<boolean>(false)
    const getProfileOfCurrentClient = async () => {
        if(typeof window !== 'undefined' && window.location){

            if (nookies.get(null)["project_full_stack:token"]) {
                setToken(nookies.get(null)["project_full_stack:token"] as string);
                api.defaults.headers.common.Authorization = `Bearer ${token? token: nookies.get(null)["project_full_stack:token"] }`
                const response = await api.get("/client")
                setProfile(response.data);
                return null;
            } else {
              setProfile(undefined);
            }
        }

    }
    useEffect(() => {
        // if (nookies.get(null)["project_full_stack:token"]) {
        //     setToken(nookies.get(null)["project_full_stack:token"] as string);
        //     api.defaults.headers.common.Authorization = `Bearer ${token? token: nookies.get(null)["project_full_stack:token"] }`
        //     const response = api.get("/client").then(response => {
        //         setProfile(response.data);
        //         return null;
        //     })
        // } else {
        //   setProfile(undefined);
        // }
        getProfileOfCurrentClient()
    }, [token, trigger])
    return (
        <AuthContext.Provider value={{
            profile,
            setProfile,
            token,
            setToken,
            trigger,
            setTrigger
        }}>
            {children}
        </AuthContext.Provider>
    )
}