version: '3.7'

services:
  project_full_stack_db:
    image: postgres
    env_file: .env
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
  
  api:
    build: ./back-end
    command: sh -c "yarn && yarn prisma migrate dev --name init && yarn build && yarn start " 
    ports:
      - 3005:3000
    depends_on:
      project_full_stack_db:
        condition: service_healthy