import { Container } from '@/components/container'
import { AuthProvider } from '@/context/AuthContext'
import StyledComponentsRegistry from '@/registry'
import '../../styles/globalstyle.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <StyledComponentsRegistry>
            <Container>
              {children}
            </Container>
          </StyledComponentsRegistry>
        </AuthProvider>
      </body>
    </html>
  )
}
